### PR TITLE
Allow Schema Registry host name to be configurable

### PR DESCRIPTION
**Pull request by willyhoang**
Summary:
The "host.name" configuration is required when running multiple
instances of schema registry so that worker instances can forward their
requests to the coordinator. We must evaluate the environment variable
in the entry point script because Marathon will not resolve it for us
before passing it in as an environment variable.

Test:
Tested that this setting SR_HOST_NAME environment variable to $HOST (and setting HOST to localhost) locally resolved schema-registry forwarding to master error.

JIRA:
https://jira.blueapron.com/browse/DI-109

### CODE REVIEW

**Comment by nikhilofthesouth** [comment]
I know you just explained this to me, but could you recap it here? So the coordinator is the "leader" instance that the workers talk to directly? Is this sort of like sticky sessions? If the publicized host name doesn't match the domain configuration for the application, I feel like the packets will get lost.

**Comment by jasonjho** [comment]
As a single master architecture, this just means that all writes to Kafka logs have to go through 1 elected master.  But reads can be served from all the workers.  I believe `host.name` is just the required config when using multiple SR nodes that has to be recorded in ZK.

**Comment by nikhilofthesouth** [comment]
So the host name isn't published to the workers, and it's just for book keeping in ZK?

**Comment by willyhoang** [comment]
I believe the host name goes to ZK but is used by the other workers so that they can forward certain requests to the coordinator/master/leader. Specifically requests that write to Kafka.

**Pull request merged**
